name: Emily Cox Photography
favicon: null
layout_spectrum: 0.9439529646188021
typography_spectrum: 0.48729379125870764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.08809037692844868
  lightness: 0.37854324700310826
  saturation: 0.1011390844359994
  rhythmicContrast: 0.5727802664041519
purpose: []
